language: go

before_script: cd $GOPATH/src/github.com/stretchr/testify/ && git checkout v1.2.2 && cd -

go:
  - "1.8.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - master

env:
  global:
    - GO111MODULE=on
